name: GitHub Actions Demo
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v2
      #- name: Cache local Maven repository (setup-java already includes cache)
      #  uses: actions/cache@v2
      #  with:
      #    path: ~/.m2/repository
      #    key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
      #    restore-keys: ${{ runner.os }}-maven-
      #test fails under default java version with message: Corrupted STDOUT by directly writing to native stream in forked JVM 1
      - name: Select Java Version
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'
          cache: 'maven'
      - name: Build and test
        run: |
          mvn package
      - run: echo "Test status is ${{ job.status }}."
      - name: Publish test reports
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: target/site/
 